config/routes.rb
Rails.application.routes.draw do

  get '/' => 'sessions#welcome'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  delete '/logout' => 'sessions#destroy'

  # Routes for Google authentication
  get '/auth/:provider/callback' => 'sessions#create'

  resources :reviews
  resources :cigars do
    resources :reviews
  end
  resources :brands, only: [:new, :show]
  resources :users


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
    has_many :cigars

    validates :name, presence: true

    def self.alphabetical
        order(:name)
      end
end

app/models/cigar.rb
class Cigar < ApplicationRecord
  belongs_to :brand
  belongs_to :user
  has_many :reviews
  has_many :users, through: :reviews

  accepts_nested_attributes_for :brand

  validates :name, :style, presence: true
  validate :not_a_duplicate
  

  def not_a_duplicate
    cigar = Cigar.find_by(style: style, brand_id: brand_id)
    if !!cigar && cigar != self
      errors.add(:name, 'has already been added for that brand!')
    end
  end

  def avg_stars
    if self.reviews.sum(:stars) >= 1
      self.reviews.average(:stars).to_f.round(1)
    else
      "No Ratings Yet!"
    end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :cigar

  validates :stars, :summary, presence: true

  scope :top, -> {where(stars: 5)}

  def self.top
    where(stars: 5)
  end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :reviews
    has_many :reviewed_cigars, through: :reviews, source: :cigar
    has_many :cigars

    has_secure_password

    validates :username, uniqueness: true, presence: true

    def self.create_by_google_omniauth(auth)
        self.find_or_create_by(username: auth[:info][:email]) do |u|
            u.password = SecureRandom.hex
        end
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    private

    def current_user
        @current_user ||=User.find_by_id(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_logged_in
        redirect_to login_path unless logged_in?
    end

    def redirect_if_not_logged_in
        redirect_to login_path if !logged_in?
    end


end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController

    def index
        @brands = Brand.all
    end

    def new
        @brand = Brand.new
    end


end

app/controllers/cigars_controller.rb
class CigarsController < ApplicationController
    before_action :redirect_if_not_logged_in

    def index
        @cigars = Cigar.all
    end

    def show
        @cigar = Cigar.find_by_id(params[:id])
    end

    def new
        @cigar = Cigar.new
        @cigar.build_brand
    end

    def create
        @cigar = Cigar.new(cigar_params)
        @cigar.user_id = session[:user_id]
        if @cigar.save
            redirect_to cigar_path(@cigar)
        else
            render :new
        end
    end

    def edit
        @cigar = Cigar.find(params[:id])
    end

    def update
        @cigar = Cigar.find(params[:id])
        @cigar.update(cigar_params)
        redirect_to cigar_path(@cigar)
    end

    private

    def cigar_params
        params.require(:cigar).permit(:name, :style, :brand_id)
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    def index
        @reviews = Review.all
    end

    def new
        @cigar = Cigar.find_by_id(params[:cigar_id])
        @review = @cigar.reviews.build
    end

    def create
        @review = current_user.reviews.build(review_params)
        if @review.save
            redirect_to review_path(@review)
        else
            render :new
        end
    end

    def show
        @review = Review.find_by_id(params[:id])
    end

    def destroy
        Review.find(params[:id]).destroy
        redirect_to cigars_path
    end

    private

    def review_params
        params.require(:review).permit(:cigar_id, :stars, :summary)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def welcome

    end

    def new

    end

    def create
        if params[:provider]
            @user = User.create_by_google_omniauth(auth)
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            @user = User.find_by(username: params[:user][:username])
        
            if @user.try(:authenticate, params[:user][:password])
                session[:user_id] = @user.id
                redirect_to user_path(@user)
            else
                flash[:error] = "Invalid login credentials. Please try again."
                redirect_to login_path
            end
        end
    end

    def destroy
        session.delete(:user_id)
        redirect_to '/'
    end

    def omniauth
        @user = User.create_by_google_omniauth(auth)
        session[:user_id] = @user.id
        redirect_to user_path(@user)
    end

    private

    def auth
        request.env['omniauth.auth']
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_logged_in, except: [:new, :create]

    def new
        if logged_in?
            @user = User.find_by(id: session[:user_id])
            redirect_to cigars_path
        else
            @user = User.new
        end
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render :new
        end
    end

    def show
        redirect_if_not_logged_in
        @user = User.find_by_id(params[:id])
        redirect_to '/' if !@user
    end

    private

    def user_params
        params.require(:user).permit(:username, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/cigars_helper.rb
module CigarsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cigars/edit.html.erb
<h1>Edit <%= @cigar.name %></h1>

<%= form_for @cigar do |f| %>
<div>
    <%= f.label 'Name:' %>
    <%= f.text_area :name %>
</div>
<br>
<div>
    <%= f.label 'Style:' %>
    <%= f.text_field :style %>
</div>
<br>

    <%= f.submit 'Save Changes' %>
<% end %>

app/views/cigars/index.html.erb
<h1>Digital Humidor</h1>

<% @cigars.each do |c| %>
    <h3><%= c.brand.name %> <%= c.name %></h3>
    <%= link_to "Leave a Review", new_cigar_review_path(c.id) %><br>
    <%= link_to "More Info", cigar_path(c.id) %>
<% end %>

app/views/cigars/new.html.erb
<%= render partial: 'layouts/errors', locals: {object: @cigar} %>

<h1>Add a Cigar to your Digital Humidor</h1>

<%= form_for(@cigar) do |f| %>
    <div>
        <%= f.label :name, 'Name:' %>
        <%= f.text_field :name %>
    </div><br>

    <div>
        <%= f.label :style, 'Style:' %>
        <%= f.text_field :style %>
    </div><br>

    <p> Brand Library: </p>

    <div>
        <%= f.collection_select :brand_id, Brand.alphabetical, :id, :name, include_blank: 'Select One' %>
    </div><br>

    <p> Add a new Brand: </p>
       
    <div>
        <%= f.fields_for :brand do |b| %>
            <%= b.label :name, 'Name:' %>
            <%= b.text_field :name %>
        <% end %>
    
    </div><br>

    <%= f.submit "Add to Humidor" %>
<% end %>

app/views/cigars/show.html.erb
<h2><%= @cigar.brand.name %> <%= @cigar.name %></h2>
<p>Style: <%= @cigar.style %></p>

<div><h3>User Reviews:</h3>
    <ul>
        <% @cigar.reviews.each do |rev| %>
            <li> <em>"<%= rev.summary %>"</em></li>
        <% end %>
    </ul>
</div>

<div>
    <h3>Average Stars: <%= @cigar.avg_stars %></h3>
</div>

<%= button_to "Edit Cigar", edit_cigar_path, method: :get %><br>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DigitalHumidor</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div>
    <%= link_to "Digtal Humidor", cigars_path %> -- 
    <%= link_to "Add a Cigar", new_cigar_path %> --
    <%= link_to "Reviews Library", reviews_path %> --
    <%= link_to "Log Out", logout_path, method: :delete %>
  </div>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/index.html.erb
<h1>Reviews Library</h1>

<ul>
<% @reviews.each do |rev| %>
    <li><%= rev.cigar.brand.name %> <%= rev.cigar.name %> - <%= rev.summary %> - <%= rev.stars %></li><br>
<% end %>
</ul>

app/views/reviews/new.html.erb
<%= render partial: 'layouts/errors', locals: {object: @review} %>

<h1>Add a Review for <%= @cigar.brand.name %> <%= @cigar.name %></h1>

<%= form_for(@review) do |f| %>
    <div>
        <%= f.label :summary, "Summary:" %>
        <%= f.text_area :summary %>
    </div><br>
    <div>
        <%= f.label :stars, "Stars:" %>
        <%= f.number_field :stars, in: 1.0..5.0 %>
    </div><br>

    <%= f.hidden_field :cigar_id %>

    <%= f.submit %>

<% end %>

app/views/reviews/show.html.erb
<h3>"<%= @review.summary %>" - <%= @review.stars %> Stars</h3>

<%= button_to "Delete Review", review_path(@review), method: :delete, data: {confirm: "Are you sure?"} %><br>

app/views/users/new.html.erb
<%= render partial: 'layouts/errors', locals: {object: @user} %>

<h1>Sign up!</h1>

<%= form_for(@user) do |f| %>
    <div>
        <%= f.label :username, 'Username:' %>
        <%= f.text_field :username %>
    </div><br>

    <div>
        <%= f.label :password, 'Password:' %>
        <%= f.password_field :password %>
    </div><br>
    <%= f.submit "Sign Up" %>
<% end %>

app/views/users/show.html.erb
Welcome <%= @user.username %>! You have signed in.